-- =============================================================
-- VoltView Migration 006: Device Mode + Reading Source
-- Run in Supabase Dashboard → SQL Editor
-- Safe: no DROP, no DELETE, no schema destruction
-- =============================================================

-- 1. Add data_mode to devices
--    'simulation' = generate fake readings (user-created devices default)
--    'device'     = expect real hardware readings
ALTER TABLE devices
  ADD COLUMN IF NOT EXISTS data_mode TEXT NOT NULL DEFAULT 'simulation';

-- 2. Add reading_source to readings
--    'simulation' = generated by demo endpoint
--    'hardware'   = sent by a real ESP32 device
ALTER TABLE readings
  ADD COLUMN IF NOT EXISTS reading_source TEXT NOT NULL DEFAULT 'simulation';

-- 3. Backfill: ESP32 (Legacy) → Device Mode + hardware readings
UPDATE devices
  SET data_mode = 'device'
  WHERE device_key = 'esp32-legacy-default';

UPDATE readings
  SET reading_source = 'hardware'
  WHERE device_id IN (
    SELECT id FROM devices WHERE device_key = 'esp32-legacy-default'
  );

-- All other existing readings (Refrigerator, TV, Washing Machine, etc.)
-- already default to reading_source = 'simulation' — no update needed.

-- 4. Useful indexes
CREATE INDEX IF NOT EXISTS idx_readings_device_source
  ON readings(device_id, reading_source);

CREATE INDEX IF NOT EXISTS idx_devices_user_mode
  ON devices(user_id, data_mode);

-- =============================================================
-- VERIFICATION QUERY — run separately after the block above
-- =============================================================
SELECT
  d.device_name,
  d.device_key,
  d.data_mode,
  COUNT(r.id)                                             AS reading_count,
  COUNT(r.id) FILTER (WHERE r.reading_source = 'hardware')    AS hw_readings,
  COUNT(r.id) FILTER (WHERE r.reading_source = 'simulation')  AS sim_readings
FROM devices d
LEFT JOIN readings r ON r.device_id = d.id
GROUP BY d.id, d.device_name, d.device_key, d.data_mode
ORDER BY d.created_at;
